###
GET https://turnos.manta.gob.ec/consultacedula/ HTTP/1.1
//https://turnos.manta.gob.ec/consultacedula/{{CEDULA}}



{
  "ok": true,
  "portal": false,
  "message": {
    "name": "",
    "fecha_nacimiento": "",
    "edad": ,
    "sexo": "",
    "discapacidad": "",
    "genero": "",
    "telefono": null,
    "telefono2": null,
    "direccion": null,
    "email": null,
    "nombre_parroquia": null,
    "barrio": null
  }
}